import type { LevelInput } from '../types'

export const level6: LevelInput = {
  id: 6,
  title: 'Conversación fluida',
  subtitle: 'Expresa ideas, opiniones y sentimientos con naturalidad.',
  cefr: 'B1–B2',
  emoji: '🗣️',
  color: 'indigo',
  lessons: [
    {
      title: 'Conectores',
      emoji: '🔗',
      items: [
        {
          en: 'however',
          es: 'sin embargo',
          kind: 'word',
          example: { en: 'The movie was long. However, I really enjoyed it.', es: 'La película fue larga. Sin embargo, la disfruté mucho.' },
          note: 'Suele ir al inicio de la frase y seguido de coma. En charla informal se usa más "but".',
        },
        {
          en: 'although',
          es: 'aunque',
          kind: 'word',
          example: { en: 'Although it was raining, we went for a walk.', es: 'Aunque estaba lloviendo, salimos a caminar.' },
          alt: ['though', 'even though'],
        },
        {
          en: 'unless',
          es: 'a menos que',
          kind: 'word',
          example: { en: 'I won\'t go unless you come with me.', es: 'No iré a menos que vengas conmigo.' },
          note: '"Unless" ya es negativo: "unless you come" equivale a "si no vienes".',
        },
        {
          en: 'That\'s why I called you.',
          es: 'Por eso te llamé.',
          kind: 'phrase',
          example: { en: 'I need your help. That\'s why I called you.', es: 'Necesito tu ayuda. Por eso te llamé.' },
        },
        {
          en: 'On the other hand, it\'s much cheaper.',
          es: 'Por otro lado, es mucho más barato.',
          kind: 'phrase',
          example: { en: 'The bus is slow. On the other hand, it\'s much cheaper.', es: 'El autobús es lento. Por otro lado, es mucho más barato.' },
        },
      ],
    },
    {
      title: 'Phrasal verbs I',
      emoji: '🧩',
      items: [
        {
          en: 'to give up',
          es: 'rendirse',
          kind: 'word',
          example: { en: 'Don\'t give up! You\'re almost there.', es: '¡No te rindas! Ya casi lo logras.' },
          note: 'También significa dejar un hábito: "give up smoking" es dejar de fumar.',
        },
        {
          en: 'to find out',
          es: 'enterarse',
          kind: 'word',
          example: { en: 'I just found out that Ana is moving.', es: 'Me acabo de enterar de que Ana se muda.' },
        },
        {
          en: 'to put off',
          es: 'posponer',
          kind: 'word',
          example: { en: 'Stop putting off your homework!', es: '¡Deja de posponer tu tarea!' },
          alt: ['to postpone'],
        },
        {
          en: 'I\'m looking forward to it.',
          es: 'Lo espero con ansias.',
          kind: 'phrase',
          example: { en: 'Are you coming to the wedding? Yes, I\'m looking forward to it!', es: '¿Vienes a la boda? ¡Sí, lo espero con ansias!' },
          note: 'Después de "look forward to" va sustantivo o -ing: "I look forward to seeing you."',
        },
        {
          en: 'We\'re running out of time.',
          es: 'Se nos está acabando el tiempo.',
          kind: 'phrase',
          example: { en: 'Hurry up! We\'re running out of time.', es: '¡Apúrate! Se nos está acabando el tiempo.' },
          note: '"Run out of" es quedarse sin algo: "We ran out of milk" es "Se nos acabó la leche".',
        },
      ],
    },
    {
      title: 'Phrasal verbs II',
      emoji: '🔧',
      items: [
        {
          en: 'to turn down',
          es: 'rechazar',
          kind: 'word',
          example: { en: 'She turned down the invitation to the party.', es: 'Ella rechazó la invitación a la fiesta.' },
          alt: ['to reject'],
        },
        {
          en: 'to show up',
          es: 'aparecer',
          kind: 'word',
          example: { en: 'He showed up two hours late.', es: 'Él apareció dos horas tarde.' },
          alt: ['to turn up'],
        },
        {
          en: 'to bring up',
          es: 'sacar un tema',
          kind: 'word',
          example: { en: 'Please don\'t bring up politics at dinner.', es: 'Por favor, no saques el tema de la política en la cena.' },
        },
        {
          en: 'She came up with a great idea.',
          es: 'Se le ocurrió una gran idea.',
          kind: 'phrase',
          example: { en: 'Ana came up with a great idea for the party.', es: 'A Ana se le ocurrió una gran idea para la fiesta.' },
          note: '"Come up with" significa idear o inventar algo, como un plan o una solución.',
        },
        {
          en: 'We get along really well.',
          es: 'Nos llevamos muy bien.',
          kind: 'phrase',
          example: { en: 'Do you like your roommate? Yes, we get along really well.', es: '¿Te cae bien tu compañero de cuarto? Sí, nos llevamos muy bien.' },
        },
      ],
    },
    {
      title: 'Dar opiniones',
      emoji: '💭',
      items: [
        {
          en: 'personally',
          es: 'personalmente',
          kind: 'word',
          example: { en: 'Personally, I prefer the book to the movie.', es: 'Personalmente, prefiero el libro a la película.' },
        },
        {
          en: 'overrated',
          es: 'sobrevalorado',
          kind: 'word',
          example: { en: 'I think that restaurant is totally overrated.', es: 'Creo que ese restaurante está totalmente sobrevalorado.' },
          note: 'Lo contrario es "underrated": infravalorado, mejor de lo que la gente cree.',
        },
        {
          en: 'point of view',
          es: 'punto de vista',
          kind: 'word',
          example: { en: 'I understand your point of view.', es: 'Entiendo tu punto de vista.' },
          alt: ['viewpoint'],
        },
        {
          en: 'If you ask me, it\'s a bad idea.',
          es: 'Si me preguntas, es una mala idea.',
          kind: 'phrase',
          example: { en: 'Moving to Alaska? If you ask me, it\'s a bad idea.', es: '¿Mudarte a Alaska? Si me preguntas, es una mala idea.' },
        },
        {
          en: 'I feel like it\'s too long.',
          es: 'Siento que es demasiado largo.',
          kind: 'phrase',
          example: { en: 'The movie is good, but I feel like it\'s too long.', es: 'La película es buena, pero siento que es demasiado larga.' },
          note: '"I feel like" + frase = me parece que. "I feel like" + -ing = tengo ganas de.',
        },
      ],
    },
    {
      title: 'Acuerdo y desacuerdo',
      emoji: '🤝',
      items: [
        {
          en: 'actually',
          es: 'en realidad',
          kind: 'word',
          example: { en: 'Actually, I don\'t agree with you.', es: 'En realidad, no estoy de acuerdo contigo.' },
          note: '¡Falso amigo! No significa "actualmente" (eso es "currently"). Sirve para corregir con suavidad.',
        },
        {
          en: 'exactly',
          es: 'exactamente',
          kind: 'word',
          example: { en: 'So we need more time? Exactly!', es: '¿Entonces necesitamos más tiempo? ¡Exactamente!' },
          alt: ['precisely'],
        },
        {
          en: 'I couldn\'t agree more.',
          es: 'Estoy totalmente de acuerdo.',
          kind: 'phrase',
          example: { en: 'This city needs more parks. I couldn\'t agree more.', es: 'Esta ciudad necesita más parques. Estoy totalmente de acuerdo.' },
          alt: ['I totally agree.', 'I completely agree.'],
          note: 'Aunque suena negativo, expresa acuerdo total: no podría estar más de acuerdo.',
        },
        {
          en: 'I\'m not so sure about that.',
          es: 'No estoy tan seguro de eso.',
          kind: 'phrase',
          example: { en: 'He\'s the best player ever. Hmm, I\'m not so sure about that.', es: 'Es el mejor jugador de la historia. Mmm, no estoy tan seguro de eso.' },
        },
        {
          en: 'Let\'s agree to disagree.',
          es: 'Aceptemos que pensamos distinto.',
          kind: 'phrase',
          example: { en: 'We\'ll never agree on this. Let\'s agree to disagree.', es: 'Nunca coincidiremos en esto. Aceptemos que pensamos distinto.' },
        },
      ],
    },
    {
      title: 'Sentimientos',
      emoji: '💗',
      items: [
        {
          en: 'thrilled',
          es: 'emocionadísimo',
          kind: 'word',
          example: { en: 'I\'m thrilled about my new job!', es: '¡Estoy emocionadísimo con mi nuevo trabajo!' },
          note: 'Es mucho más intenso que "happy" o "excited".',
        },
        {
          en: 'overwhelmed',
          es: 'abrumado',
          kind: 'word',
          example: { en: 'I feel overwhelmed with so much to do.', es: 'Me siento abrumado con tantas cosas por hacer.' },
        },
        {
          en: 'embarrassed',
          es: 'avergonzado',
          kind: 'word',
          example: { en: 'I was so embarrassed when I fell in the street.', es: 'Me dio muchísima vergüenza cuando me caí en la calle.' },
          note: '¡Falso amigo! "Embarazada" en inglés se dice "pregnant".',
        },
        {
          en: 'I\'m fed up with this.',
          es: 'Estoy harto de esto.',
          kind: 'phrase',
          example: { en: 'The neighbors are loud again. I\'m fed up with this!', es: 'Los vecinos hacen ruido otra vez. ¡Estoy harto de esto!' },
          alt: ['I\'m sick of this.'],
        },
        {
          en: 'What a relief!',
          es: '¡Qué alivio!',
          kind: 'phrase',
          example: { en: 'We found your dog. What a relief!', es: 'Encontramos a tu perro. ¡Qué alivio!' },
        },
      ],
    },
    {
      title: 'Modismos',
      emoji: '🍰',
      items: [
        {
          en: 'It\'s a piece of cake.',
          es: 'Es pan comido.',
          kind: 'phrase',
          example: { en: 'Is the exam hard? No, it\'s a piece of cake.', es: '¿El examen es difícil? No, es pan comido.' },
        },
        {
          en: 'It costs an arm and a leg.',
          es: 'Cuesta un ojo de la cara.',
          kind: 'phrase',
          example: { en: 'I love that car, but it costs an arm and a leg.', es: 'Me encanta ese auto, pero cuesta un ojo de la cara.' },
        },
        {
          en: 'Speak of the devil!',
          es: '¡Hablando del rey de Roma!',
          kind: 'phrase',
          example: { en: 'Speak of the devil! We were just talking about you.', es: '¡Hablando del rey de Roma! Justo estábamos hablando de ti.' },
          note: 'Se dice cuando aparece justo la persona de la que estabas hablando.',
        },
        {
          en: 'My lips are sealed.',
          es: 'Soy una tumba.',
          kind: 'phrase',
          example: { en: 'Don\'t tell anyone, okay? Don\'t worry, my lips are sealed.', es: 'No le digas a nadie, ¿sí? Tranquilo, soy una tumba.' },
        },
        {
          en: 'I\'m feeling under the weather.',
          es: 'Me siento un poco indispuesto.',
          kind: 'phrase',
          example: { en: 'I\'m staying home today. I\'m feeling under the weather.', es: 'Hoy me quedo en casa. Me siento un poco indispuesto.' },
          note: 'No tiene que ver con el clima: significa sentirse un poco enfermo.',
        },
      ],
    },
    {
      title: 'Charla casual',
      emoji: '☕',
      items: [
        {
          en: 'small talk',
          es: 'charla casual',
          kind: 'word',
          example: { en: 'I\'m not very good at small talk.', es: 'No soy muy bueno para la charla casual.' },
          note: 'Conversación ligera sobre temas como el clima o el fin de semana.',
        },
        {
          en: 'to catch up',
          es: 'ponerse al día',
          kind: 'word',
          example: { en: 'Let\'s get coffee and catch up!', es: '¡Tomemos un café y pongámonos al día!' },
        },
        {
          en: 'to run into',
          es: 'encontrarse por casualidad',
          kind: 'word',
          example: { en: 'I ran into my old teacher at the mall.', es: 'Me encontré por casualidad con mi antiguo profesor en el centro comercial.' },
          alt: ['to bump into'],
        },
        {
          en: 'What have you been up to?',
          es: '¿Qué has hecho últimamente?',
          kind: 'phrase',
          example: { en: 'Hey, Mike! What have you been up to?', es: '¡Hola, Mike! ¿Qué has hecho últimamente?' },
          note: 'Una respuesta típica es "Not much, just working."',
        },
        {
          en: 'It was great talking to you.',
          es: 'Fue un gusto hablar contigo.',
          kind: 'phrase',
          example: { en: 'I have to go now. It was great talking to you!', es: 'Ya me tengo que ir. ¡Fue un gusto hablar contigo!' },
          alt: ['It was nice talking to you.'],
        },
      ],
    },
    {
      title: 'Consejos',
      emoji: '💡',
      items: [
        {
          en: 'advice',
          es: 'consejo',
          kind: 'word',
          example: { en: 'Can I give you some advice?', es: '¿Puedo darte un consejo?' },
          note: 'Es incontable: "some advice" o "a piece of advice", nunca "an advice".',
        },
        {
          en: 'should',
          es: 'debería',
          kind: 'word',
          example: { en: 'You should get more sleep.', es: 'Deberías dormir más.' },
        },
        {
          en: 'If I were you, I\'d wait.',
          es: 'Yo que tú, esperaría.',
          kind: 'phrase',
          example: { en: 'Should I buy it now? If I were you, I\'d wait.', es: '¿Lo compro ahora? Yo que tú, esperaría.' },
          note: 'Se usa "were" con todas las personas: "If I were you".',
        },
        {
          en: 'You\'d better leave now.',
          es: 'Más vale que te vayas ya.',
          kind: 'phrase',
          example: { en: 'It\'s getting dark. You\'d better leave now.', es: 'Está oscureciendo. Más vale que te vayas ya.' },
          alt: ['You had better leave now.'],
          note: '"You\'d better" viene de "you had better" y suena a advertencia.',
        },
        {
          en: 'Why don\'t you take a break?',
          es: '¿Por qué no tomas un descanso?',
          kind: 'phrase',
          example: { en: 'You look tired. Why don\'t you take a break?', es: 'Te ves cansado. ¿Por qué no tomas un descanso?' },
        },
      ],
    },
    {
      title: 'Ganar tiempo al hablar',
      emoji: '⏳',
      items: [
        {
          en: 'well',
          es: 'pues',
          kind: 'word',
          example: { en: 'Well, I\'m not really sure.', es: 'Pues, no estoy muy seguro.' },
          note: 'Muletilla muy común para pensar un momento antes de responder.',
        },
        {
          en: 'you know',
          es: '¿sabes?',
          kind: 'word',
          example: { en: 'It was, you know, a little weird.', es: 'Fue, ¿sabes?, un poco raro.' },
        },
        {
          en: 'I mean',
          es: 'o sea',
          kind: 'word',
          example: { en: 'It\'s good. I mean, it\'s not perfect.', es: 'Está bien. O sea, no es perfecto.' },
          note: 'Sirve para aclarar o corregir lo que acabas de decir.',
        },
        {
          en: 'Let me think.',
          es: 'Déjame pensar.',
          kind: 'phrase',
          example: { en: 'My favorite movie? Let me think.', es: '¿Mi película favorita? Déjame pensar.' },
          alt: ['Let me see.'],
        },
        {
          en: 'How can I put it?',
          es: '¿Cómo lo digo?',
          kind: 'phrase',
          example: { en: 'The food was, how can I put it, interesting.', es: 'La comida estaba, ¿cómo lo digo?, interesante.' },
          alt: ['How should I put it?'],
        },
      ],
    },
  ],
}
