import type { LevelInput } from '../types'

export const level4: LevelInput = {
  id: 4,
  title: 'De viaje',
  subtitle: 'Viaja con confianza: del aeropuerto al hotel y a la playa.',
  cefr: 'A2',
  emoji: '✈️',
  color: 'amber',
  lessons: [
    {
      title: 'En el aeropuerto',
      emoji: '🛫',
      items: [
        {
          en: 'boarding pass',
          es: 'tarjeta de embarque',
          kind: 'word',
          example: { en: 'Please have your boarding pass ready.', es: 'Por favor, tenga lista su tarjeta de embarque.' },
        },
        {
          en: 'gate',
          es: 'puerta de embarque',
          kind: 'word',
          example: { en: 'Our flight leaves from gate 12.', es: 'Nuestro vuelo sale de la puerta 12.' },
          alt: ['boarding gate'],
          note: '"Gate" es la puerta de embarque; la puerta de una casa o un cuarto es "door".',
        },
        {
          en: 'suitcase',
          es: 'maleta',
          kind: 'word',
          example: { en: 'My suitcase is very heavy.', es: 'Mi maleta está muy pesada.' },
        },
        {
          en: 'Where is the check-in counter?',
          es: '¿Dónde está el mostrador de check-in?',
          kind: 'phrase',
          example: { en: 'Excuse me, where is the check-in counter?', es: 'Disculpe, ¿dónde está el mostrador de check-in?' },
        },
        {
          en: 'How many bags are you checking?',
          es: '¿Cuántas maletas va a documentar?',
          kind: 'phrase',
          example: { en: 'How many bags are you checking? — Just one.', es: '¿Cuántas maletas va a documentar? —Solo una.' },
          note: '"To check a bag" es documentar (o despachar) una maleta para que vaya en la bodega del avión.',
        },
      ],
    },
    {
      title: 'En el avión',
      emoji: '💺',
      items: [
        {
          en: 'seat belt',
          es: 'cinturón de seguridad',
          kind: 'word',
          example: { en: 'Please fasten your seat belt.', es: 'Por favor, abróchese el cinturón de seguridad.' },
          alt: ['seatbelt'],
        },
        {
          en: 'aisle seat',
          es: 'asiento de pasillo',
          kind: 'word',
          example: { en: 'I prefer an aisle seat on long flights.', es: 'Prefiero un asiento de pasillo en vuelos largos.' },
          note: 'En "aisle" la "s" es muda: se pronuncia "ail". El de ventana es "window seat".',
        },
        {
          en: 'flight attendant',
          es: 'auxiliar de vuelo',
          kind: 'word',
          example: { en: 'The flight attendant brought me some water.', es: 'La auxiliar de vuelo me trajo agua.' },
        },
        {
          en: 'Can I have a blanket, please?',
          es: '¿Me puede dar una manta, por favor?',
          kind: 'phrase',
          example: { en: "It's cold. Can I have a blanket, please?", es: 'Hace frío. ¿Me puede dar una manta, por favor?' },
          alt: ['Could I have a blanket, please?', 'Can I get a blanket, please?'],
        },
        {
          en: "We're about to land.",
          es: 'Estamos a punto de aterrizar.',
          kind: 'phrase',
          example: { en: "Wake up! We're about to land.", es: '¡Despierta! Estamos a punto de aterrizar.' },
          note: '"To land" es aterrizar y "to take off" es despegar.',
        },
      ],
    },
    {
      title: 'Migración y aduana',
      emoji: '🛂',
      items: [
        {
          en: 'passport',
          es: 'pasaporte',
          kind: 'word',
          example: { en: 'Can I see your passport, please?', es: '¿Puedo ver su pasaporte, por favor?' },
        },
        {
          en: 'customs',
          es: 'aduana',
          kind: 'word',
          example: { en: 'We went through customs very quickly.', es: 'Pasamos la aduana muy rápido.' },
          note: '"Customs" (aduana) siempre lleva S al final; "custom" significa costumbre.',
        },
        {
          en: 'What is the purpose of your visit?',
          es: '¿Cuál es el motivo de su visita?',
          kind: 'phrase',
          example: { en: 'What is the purpose of your visit? — Tourism.', es: '¿Cuál es el motivo de su visita? —Turismo.' },
        },
        {
          en: "I'm here on vacation.",
          es: 'Estoy aquí de vacaciones.',
          kind: 'phrase',
          example: { en: "I'm here on vacation for two weeks.", es: 'Estoy aquí de vacaciones por dos semanas.' },
          alt: ["I'm on vacation.", "I'm here on holiday."],
          note: 'En EE. UU. se dice "vacation"; en el Reino Unido, "holiday".',
        },
        {
          en: 'I have nothing to declare.',
          es: 'No tengo nada que declarar.',
          kind: 'phrase',
          example: { en: 'No, sir. I have nothing to declare.', es: 'No, señor. No tengo nada que declarar.' },
        },
      ],
    },
    {
      title: 'En el hotel',
      emoji: '🏨',
      items: [
        {
          en: 'front desk',
          es: 'recepción',
          kind: 'word',
          example: { en: 'You can leave your bags at the front desk.', es: 'Puede dejar sus maletas en la recepción.' },
          alt: ['reception', 'reception desk'],
          note: 'En EE. UU. se dice "front desk"; "reception" es más común en el Reino Unido.',
        },
        {
          en: 'room key',
          es: 'llave de la habitación',
          kind: 'word',
          example: { en: 'I left my room key inside the room.', es: 'Dejé la llave de la habitación adentro del cuarto.' },
        },
        {
          en: 'double room',
          es: 'habitación doble',
          kind: 'word',
          example: { en: 'We need a double room for three nights.', es: 'Necesitamos una habitación doble por tres noches.' },
        },
        {
          en: 'Is breakfast included?',
          es: '¿El desayuno está incluido?',
          kind: 'phrase',
          example: { en: 'Is breakfast included in the price?', es: '¿El desayuno está incluido en el precio?' },
        },
        {
          en: 'What time is checkout?',
          es: '¿A qué hora hay que dejar la habitación?',
          kind: 'phrase',
          example: { en: 'What time is checkout? — At eleven.', es: '¿A qué hora hay que dejar la habitación? —A las once.' },
          alt: ['What time is check-out?', 'What time do I have to check out?'],
        },
      ],
    },
    {
      title: 'Reservas',
      emoji: '📅',
      items: [
        {
          en: 'reservation',
          es: 'reserva',
          kind: 'word',
          example: { en: 'We have a reservation for two nights.', es: 'Tenemos una reserva por dos noches.' },
          alt: ['booking'],
          note: 'En EE. UU. se usa más "reservation"; "booking" es muy común en el Reino Unido.',
        },
        {
          en: 'to book',
          es: 'reservar',
          kind: 'word',
          example: { en: 'I booked a hotel near the beach.', es: 'Reservé un hotel cerca de la playa.' },
          alt: ['to reserve'],
          note: 'Como sustantivo, "book" es libro; como verbo, "to book" es reservar.',
        },
        {
          en: 'Do you have any rooms available?',
          es: '¿Tiene habitaciones disponibles?',
          kind: 'phrase',
          example: { en: 'Do you have any rooms available this weekend?', es: '¿Tiene habitaciones disponibles este fin de semana?' },
        },
        {
          en: 'I have a reservation for tonight.',
          es: 'Tengo una reserva para esta noche.',
          kind: 'phrase',
          example: { en: 'Good evening. I have a reservation for tonight.', es: 'Buenas noches. Tengo una reserva para esta noche.' },
        },
        {
          en: "I'd like to cancel my reservation.",
          es: 'Quisiera cancelar mi reserva.',
          kind: 'phrase',
          example: { en: "I'd like to cancel my reservation for Friday.", es: 'Quisiera cancelar mi reserva del viernes.' },
        },
      ],
    },
    {
      title: 'Turismo',
      emoji: '📸',
      items: [
        {
          en: 'tour guide',
          es: 'guía turístico',
          kind: 'word',
          example: { en: 'Our tour guide speaks English and Spanish.', es: 'Nuestro guía turístico habla inglés y español.' },
          alt: ['guide'],
        },
        {
          en: 'to go sightseeing',
          es: 'hacer turismo',
          kind: 'word',
          example: { en: "Tomorrow we're going sightseeing in the old town.", es: 'Mañana vamos a hacer turismo en el centro histórico.' },
        },
        {
          en: 'souvenir',
          es: 'recuerdo (de viaje)',
          kind: 'word',
          example: { en: 'I bought a souvenir for my mom.', es: 'Compré un recuerdo para mi mamá.' },
          note: '"Souvenir" es un objeto; un recuerdo en la mente se dice "memory".',
        },
        {
          en: 'Can you take a picture of us?',
          es: '¿Nos puede tomar una foto?',
          kind: 'phrase',
          example: { en: 'Excuse me, can you take a picture of us?', es: 'Disculpe, ¿nos puede tomar una foto?' },
          alt: ['Could you take a picture of us?', 'Can you take a photo of us?'],
        },
        {
          en: 'What time does the tour start?',
          es: '¿A qué hora empieza el recorrido?',
          kind: 'phrase',
          example: { en: 'What time does the tour start tomorrow?', es: '¿A qué hora empieza el recorrido mañana?' },
        },
      ],
    },
    {
      title: 'Alquilar un auto',
      emoji: '🚗',
      items: [
        {
          en: "driver's license",
          es: 'licencia de conducir',
          kind: 'word',
          example: { en: "You need a driver's license to rent a car.", es: 'Necesitas licencia de conducir para alquilar un auto.' },
          alt: ['driver license', 'driving licence'],
          note: 'En el Reino Unido se dice "driving licence".',
        },
        {
          en: 'car insurance',
          es: 'seguro de auto',
          kind: 'word',
          example: { en: 'Do I need car insurance?', es: '¿Necesito seguro de auto?' },
          alt: ['auto insurance'],
        },
        {
          en: 'rental car',
          es: 'auto de alquiler',
          kind: 'word',
          example: { en: 'We picked up the rental car at the airport.', es: 'Recogimos el auto de alquiler en el aeropuerto.' },
        },
        {
          en: "I'd like to rent a car for a week.",
          es: 'Quisiera alquilar un auto por una semana.',
          kind: 'phrase',
          example: { en: "Hello, I'd like to rent a car for a week.", es: 'Hola, quisiera alquilar un auto por una semana.' },
        },
        {
          en: 'Where do I return the car?',
          es: '¿Dónde devuelvo el auto?',
          kind: 'phrase',
          example: { en: 'Where do I return the car on Sunday?', es: '¿Dónde devuelvo el auto el domingo?' },
        },
      ],
    },
    {
      title: 'Emergencias',
      emoji: '🚨',
      items: [
        {
          en: 'help',
          es: 'ayuda',
          kind: 'word',
          example: { en: "Help! My friend can't swim!", es: '¡Ayuda! ¡Mi amigo no sabe nadar!' },
          note: 'Para pedir auxilio se grita "Help!". En EE. UU. el número de emergencias es el 911.',
        },
        {
          en: 'ambulance',
          es: 'ambulancia',
          kind: 'word',
          example: { en: 'Please call an ambulance right now.', es: 'Por favor, llame a una ambulancia ahora mismo.' },
        },
        {
          en: 'fire',
          es: 'incendio',
          kind: 'word',
          example: { en: "There's a fire on the third floor!", es: '¡Hay un incendio en el tercer piso!' },
        },
        {
          en: 'Call the police!',
          es: '¡Llame a la policía!',
          kind: 'phrase',
          example: { en: 'Someone stole my phone! Call the police!', es: '¡Alguien me robó el teléfono! ¡Llame a la policía!' },
        },
        {
          en: "It's an emergency!",
          es: '¡Es una emergencia!',
          kind: 'phrase',
          example: { en: "Please hurry, it's an emergency!", es: '¡Por favor, apúrese, es una emergencia!' },
        },
      ],
    },
    {
      title: 'En la playa',
      emoji: '🏖️',
      items: [
        {
          en: 'sunscreen',
          es: 'protector solar',
          kind: 'word',
          example: { en: "Don't forget to put on sunscreen.", es: 'No olvides ponerte protector solar.' },
          alt: ['sunblock'],
        },
        {
          en: 'lifeguard',
          es: 'salvavidas (persona)',
          kind: 'word',
          example: { en: "There's no lifeguard on this beach.", es: 'No hay salvavidas en esta playa.' },
          note: '"Lifeguard" es la persona; el chaleco salvavidas es "life jacket".',
        },
        {
          en: 'wave',
          es: 'ola',
          kind: 'word',
          example: { en: 'The waves are very big today.', es: 'Las olas están muy grandes hoy.' },
          note: 'Como verbo, "to wave" significa saludar con la mano.',
        },
        {
          en: 'Is it safe to swim here?',
          es: '¿Es seguro nadar aquí?',
          kind: 'phrase',
          example: { en: 'Excuse me, is it safe to swim here?', es: 'Disculpe, ¿es seguro nadar aquí?' },
        },
        {
          en: 'I got a sunburn.',
          es: 'Me quemé con el sol.',
          kind: 'phrase',
          example: { en: 'Ouch! I got a sunburn yesterday.', es: '¡Ay! Ayer me quemé con el sol.' },
          alt: ['I got sunburned.'],
        },
      ],
    },
    {
      title: 'Problemas de viaje',
      emoji: '🧳',
      items: [
        {
          en: 'delayed',
          es: 'retrasado',
          kind: 'word',
          example: { en: 'Our flight is delayed by two hours.', es: 'Nuestro vuelo tiene dos horas de retraso.' },
        },
        {
          en: 'canceled',
          es: 'cancelado',
          kind: 'word',
          example: { en: 'Our train was canceled because of the snow.', es: 'Nuestro tren fue cancelado por la nieve.' },
          alt: ['cancelled'],
          note: '"Canceled" con una L es la forma de EE. UU.; "cancelled" es la británica.',
        },
        {
          en: 'to miss',
          es: 'perder (un vuelo o bus)',
          kind: 'word',
          example: { en: "Hurry up or we'll miss the flight!", es: '¡Apúrate o vamos a perder el vuelo!' },
          note: '"To miss" es perder un vuelo o un bus; "to lose" es perder un objeto.',
        },
        {
          en: "My suitcase didn't arrive.",
          es: 'Mi maleta no llegó.',
          kind: 'phrase',
          example: { en: "My suitcase didn't arrive. Where can I report it?", es: 'Mi maleta no llegó. ¿Dónde puedo reportarlo?' },
          alt: ["My bag didn't arrive.", "My luggage didn't arrive."],
        },
        {
          en: 'I lost my passport.',
          es: 'Perdí mi pasaporte.',
          kind: 'phrase',
          example: { en: 'I lost my passport. What should I do?', es: 'Perdí mi pasaporte. ¿Qué debo hacer?' },
        },
      ],
    },
  ],
}
