import type { LevelInput } from '../types'

export const level2: LevelInput = {
  id: 2,
  title: 'Mi día a día',
  subtitle: 'Habla de tu rutina, tu casa, la comida y el clima.',
  cefr: 'A1',
  emoji: '☀️',
  color: 'sky',
  lessons: [
    {
      title: 'Rutina de la mañana',
      emoji: '⏰',
      items: [
        {
          en: 'to wake up',
          es: 'despertarse',
          kind: 'word',
          example: { en: 'I wake up at six every day.', es: 'Me despierto a las seis todos los días.' },
          note: '"To wake up" es despertarse; "to get up" es levantarse de la cama.',
        },
        {
          en: 'to get up',
          es: 'levantarse',
          kind: 'word',
          example: { en: 'On Sundays I get up at ten.', es: 'Los domingos me levanto a las diez.' },
        },
        {
          en: 'to have breakfast',
          es: 'desayunar',
          kind: 'word',
          example: { en: 'We have breakfast together every morning.', es: 'Desayunamos juntos todas las mañanas.' },
          alt: ['to eat breakfast'],
          note: 'Las comidas van con "have": have breakfast, have lunch, have dinner.',
        },
        {
          en: 'I take a shower every morning.',
          es: 'Me ducho todas las mañanas.',
          kind: 'phrase',
          example: { en: 'I take a shower every morning before work.', es: 'Me ducho todas las mañanas antes del trabajo.' },
          alt: ['I shower every morning.'],
        },
        {
          en: 'I brush my teeth after breakfast.',
          es: 'Me cepillo los dientes después del desayuno.',
          kind: 'phrase',
          example: { en: 'I brush my teeth after breakfast, then I go to work.', es: 'Me cepillo los dientes después del desayuno y luego voy al trabajo.' },
          note: 'Con partes del cuerpo se usa el posesivo: "my teeth", no "the teeth".',
        },
      ],
    },
    {
      title: 'En casa',
      emoji: '🏠',
      items: [
        {
          en: 'kitchen',
          es: 'cocina',
          kind: 'word',
          example: { en: 'My mom is cooking in the kitchen.', es: 'Mi mamá está cocinando en la cocina.' },
          note: 'No confundas "kitchen" (cocina) con "chicken" (pollo).',
        },
        {
          en: 'bedroom',
          es: 'dormitorio',
          kind: 'word',
          example: { en: 'Our house has three bedrooms.', es: 'Nuestra casa tiene tres dormitorios.' },
        },
        {
          en: 'living room',
          es: 'sala',
          kind: 'word',
          example: { en: 'The sofa is in the living room.', es: 'El sofá está en la sala.' },
        },
        {
          en: 'bathroom',
          es: 'baño',
          kind: 'word',
          example: { en: 'The bathroom is upstairs, next to my bedroom.', es: 'El baño está arriba, al lado de mi dormitorio.' },
        },
        {
          en: 'Make yourself at home.',
          es: 'Siéntete como en casa.',
          kind: 'phrase',
          example: { en: 'Come in, please. Make yourself at home.', es: 'Pasa, por favor. Siéntete como en casa.' },
        },
      ],
    },
    {
      title: 'Comida',
      emoji: '🍎',
      items: [
        {
          en: 'bread',
          es: 'pan',
          kind: 'word',
          example: { en: 'I eat bread with butter for breakfast.', es: 'Como pan con mantequilla en el desayuno.' },
        },
        {
          en: 'chicken',
          es: 'pollo',
          kind: 'word',
          example: { en: 'I love chicken with rice.', es: 'Me encanta el pollo con arroz.' },
        },
        {
          en: 'vegetables',
          es: 'verduras',
          kind: 'word',
          example: { en: "My kids don't like vegetables.", es: 'A mis hijos no les gustan las verduras.' },
          alt: ['veggies'],
        },
        {
          en: "I'm very hungry.",
          es: 'Tengo mucha hambre.',
          kind: 'phrase',
          example: { en: "I'm very hungry. Let's eat!", es: 'Tengo mucha hambre. ¡Comamos!' },
          alt: ["I'm so hungry.", "I'm really hungry."],
          note: 'Se usa "to be": "I\'m hungry". Nunca "I have hunger".',
        },
        {
          en: "What's for dinner?",
          es: '¿Qué hay de cenar?',
          kind: 'phrase',
          example: { en: "Hi, Mom, I'm home! What's for dinner?", es: '¡Hola, mamá, ya llegué! ¿Qué hay de cenar?' },
        },
      ],
    },
    {
      title: 'Bebidas',
      emoji: '☕',
      items: [
        {
          en: 'water',
          es: 'agua',
          kind: 'word',
          example: { en: 'Drink more water when it is hot.', es: 'Toma más agua cuando hace calor.' },
        },
        {
          en: 'coffee',
          es: 'café',
          kind: 'word',
          example: { en: 'I drink two cups of coffee a day.', es: 'Tomo dos tazas de café al día.' },
        },
        {
          en: 'juice',
          es: 'jugo',
          kind: 'word',
          example: { en: 'My son drinks orange juice with breakfast.', es: 'Mi hijo toma jugo de naranja en el desayuno.' },
        },
        {
          en: "I'm so thirsty!",
          es: '¡Tengo mucha sed!',
          kind: 'phrase',
          example: { en: "I'm so thirsty! Is there any water?", es: '¡Tengo mucha sed! ¿Hay agua?' },
          alt: ["I'm very thirsty.", "I'm really thirsty."],
        },
        {
          en: 'Would you like a cup of tea?',
          es: '¿Quieres una taza de té?',
          kind: 'phrase',
          example: { en: 'Come in! Would you like a cup of tea?', es: '¡Pasa! ¿Quieres una taza de té?' },
          note: '"Would you like" es la forma amable de ofrecer algo; es más cortés que "Do you want".',
        },
      ],
    },
    {
      title: 'Días y meses',
      emoji: '📅',
      items: [
        {
          en: 'Monday',
          es: 'lunes',
          kind: 'word',
          example: { en: 'I work from Monday to Friday.', es: 'Trabajo de lunes a viernes.' },
          note: 'Días y meses van con mayúscula. Se dice "on Monday" (el lunes) pero "in January" (en enero).',
        },
        {
          en: 'weekend',
          es: 'fin de semana',
          kind: 'word',
          example: { en: 'I sleep late on the weekend.', es: 'Duermo hasta tarde el fin de semana.' },
        },
        {
          en: 'January',
          es: 'enero',
          kind: 'word',
          example: { en: 'The year starts in January.', es: 'El año empieza en enero.' },
        },
        {
          en: 'What day is it today?',
          es: '¿Qué día es hoy?',
          kind: 'phrase',
          example: { en: "What day is it today? — It's Wednesday.", es: '¿Qué día es hoy? —Es miércoles.' },
          alt: ['What day is today?'],
        },
        {
          en: 'When is your birthday?',
          es: '¿Cuándo es tu cumpleaños?',
          kind: 'phrase',
          example: { en: "When is your birthday? — It's in March.", es: '¿Cuándo es tu cumpleaños? —Es en marzo.' },
        },
      ],
    },
    {
      title: 'La hora',
      emoji: '🕒',
      items: [
        {
          en: "o'clock",
          es: 'en punto',
          kind: 'word',
          example: { en: "The movie starts at eight o'clock.", es: 'La película empieza a las ocho en punto.' },
        },
        {
          en: 'noon',
          es: 'mediodía',
          kind: 'word',
          example: { en: 'We have lunch at noon.', es: 'Almorzamos al mediodía.' },
          alt: ['midday'],
        },
        {
          en: 'early',
          es: 'temprano',
          kind: 'word',
          example: { en: 'I go to bed early on Sundays.', es: 'Me acuesto temprano los domingos.' },
        },
        {
          en: 'What time is it?',
          es: '¿Qué hora es?',
          kind: 'phrase',
          example: { en: "What time is it? — It's three o'clock.", es: '¿Qué hora es? —Son las tres en punto.' },
        },
        {
          en: "It's half past seven.",
          es: 'Son las siete y media.',
          kind: 'phrase',
          example: { en: "Hurry up! It's half past seven.", es: '¡Apúrate! Son las siete y media.' },
          alt: ["It's seven thirty."],
          note: '"Half past" = y media; "a quarter past" = y cuarto; "a quarter to" = menos cuarto.',
        },
      ],
    },
    {
      title: 'El clima',
      emoji: '🌦️',
      items: [
        {
          en: 'sunny',
          es: 'soleado',
          kind: 'word',
          example: { en: "It's a sunny day, let's go to the park.", es: 'Es un día soleado, vamos al parque.' },
        },
        {
          en: 'cloudy',
          es: 'nublado',
          kind: 'word',
          example: { en: "It's cloudy, but it isn't raining.", es: 'Está nublado, pero no está lloviendo.' },
        },
        {
          en: 'to rain',
          es: 'llover',
          kind: 'word',
          example: { en: 'It rains a lot in April.', es: 'Llueve mucho en abril.' },
        },
        {
          en: "What's the weather like today?",
          es: '¿Qué tiempo hace hoy?',
          kind: 'phrase',
          example: { en: "What's the weather like today? — It's sunny and hot.", es: '¿Qué tiempo hace hoy? —Hace sol y calor.' },
          alt: ["How's the weather today?"],
          note: 'Error común: "How is the weather like?". Lo correcto es "What\'s the weather like?".',
        },
        {
          en: "It's very cold today.",
          es: 'Hoy hace mucho frío.',
          kind: 'phrase',
          example: { en: "It's very cold today, so I'm staying home.", es: 'Hoy hace mucho frío, así que me quedo en casa.' },
          note: 'Para el clima se usa "it is": "It\'s cold" = Hace frío. Nunca "It makes cold".',
        },
      ],
    },
    {
      title: 'Ropa',
      emoji: '👕',
      items: [
        {
          en: 'shirt',
          es: 'camisa',
          kind: 'word',
          example: { en: 'He wears a white shirt to work.', es: 'Él usa camisa blanca para ir al trabajo.' },
        },
        {
          en: 'pants',
          es: 'pantalones',
          kind: 'word',
          example: { en: 'These pants are too long for me.', es: 'Estos pantalones me quedan demasiado largos.' },
          alt: ['trousers'],
          note: 'En EE. UU. "pants" son pantalones; en Reino Unido "pants" es ropa interior.',
        },
        {
          en: 'shoes',
          es: 'zapatos',
          kind: 'word',
          example: { en: 'I need new shoes for the party.', es: 'Necesito zapatos nuevos para la fiesta.' },
        },
        {
          en: 'What should I wear today?',
          es: '¿Qué me pongo hoy?',
          kind: 'phrase',
          example: { en: "It's raining. What should I wear today?", es: 'Está lloviendo. ¿Qué me pongo hoy?' },
          note: '"To wear" = llevar puesto; "to put on" = ponerse una prenda.',
        },
        {
          en: 'Put on your coat.',
          es: 'Ponte el abrigo.',
          kind: 'phrase',
          example: { en: "It's cold outside. Put on your coat!", es: 'Hace frío afuera. ¡Ponte el abrigo!' },
        },
      ],
    },
    {
      title: 'Emociones',
      emoji: '😊',
      items: [
        {
          en: 'happy',
          es: 'feliz',
          kind: 'word',
          example: { en: "I'm happy because it's Friday!", es: '¡Estoy feliz porque es viernes!' },
        },
        {
          en: 'sad',
          es: 'triste',
          kind: 'word',
          example: { en: 'She is sad because her dog is sick.', es: 'Ella está triste porque su perro está enfermo.' },
        },
        {
          en: 'tired',
          es: 'cansado',
          kind: 'word',
          example: { en: "I'm always tired after work.", es: 'Siempre estoy cansado después del trabajo.' },
        },
        {
          en: 'How are you feeling today?',
          es: '¿Cómo te sientes hoy?',
          kind: 'phrase',
          example: { en: 'How are you feeling today? — Much better, thanks.', es: '¿Cómo te sientes hoy? —Mucho mejor, gracias.' },
          alt: ['How do you feel today?'],
        },
        {
          en: "I'm really bored.",
          es: 'Estoy muy aburrido.',
          kind: 'phrase',
          example: { en: "There's nothing on TV. I'm really bored.", es: 'No hay nada en la tele. Estoy muy aburrido.' },
          alt: ["I'm very bored.", "I'm so bored."],
          note: 'Ojo: "I\'m bored" = estoy aburrido; "I\'m boring" = soy aburrido.',
        },
      ],
    },
    {
      title: 'Tiempo libre',
      emoji: '🎨',
      items: [
        {
          en: 'hobby',
          es: 'pasatiempo',
          kind: 'word',
          example: { en: 'My favorite hobby is painting.', es: 'Mi pasatiempo favorito es pintar.' },
        },
        {
          en: 'to read',
          es: 'leer',
          kind: 'word',
          example: { en: 'I like to read before bed.', es: 'Me gusta leer antes de dormir.' },
        },
        {
          en: 'to watch TV',
          es: 'ver televisión',
          kind: 'word',
          example: { en: 'We watch TV after dinner.', es: 'Vemos televisión después de cenar.' },
          alt: ['to watch television'],
        },
        {
          en: 'What do you do in your free time?',
          es: '¿Qué haces en tu tiempo libre?',
          kind: 'phrase',
          example: { en: 'What do you do in your free time? — I play the guitar.', es: '¿Qué haces en tu tiempo libre? —Toco la guitarra.' },
        },
        {
          en: 'I love playing soccer.',
          es: 'Me encanta jugar al fútbol.',
          kind: 'phrase',
          example: { en: 'I love playing soccer with my friends.', es: 'Me encanta jugar al fútbol con mis amigos.' },
          alt: ['I love to play soccer.'],
          note: 'En EE. UU. el fútbol es "soccer"; "football" es el fútbol americano.',
        },
      ],
    },
  ],
}
