import type { LevelInput } from '../types'

export const level5: LevelInput = {
  id: 5,
  title: 'Trabajo y estudios',
  subtitle: 'Comunícate con seguridad en la oficina, en clase y en entrevistas.',
  cefr: 'B1',
  emoji: '💼',
  color: 'rose',
  lessons: [
    {
      title: 'Profesiones',
      emoji: '👷',
      items: [
        {
          en: 'lawyer',
          es: 'abogado',
          kind: 'word',
          example: { en: 'My sister is a lawyer at a big firm.', es: 'Mi hermana es abogada en un bufete grande.' },
        },
        {
          en: 'engineer',
          es: 'ingeniero',
          kind: 'word',
          example: { en: 'He works as an engineer for a car company.', es: 'Trabaja como ingeniero en una empresa de autos.' },
          note: 'El acento va en la última sílaba: en-gi-NEER.',
        },
        {
          en: 'accountant',
          es: 'contador',
          kind: 'word',
          example: { en: 'Our accountant helps us with taxes every year.', es: 'Nuestro contador nos ayuda con los impuestos cada año.' },
        },
        {
          en: 'What do you do for a living?',
          es: '¿A qué te dedicas?',
          kind: 'phrase',
          example: { en: "What do you do for a living? — I'm a nurse.", es: '¿A qué te dedicas? —Soy enfermera.' },
          alt: ['What do you do?'],
          note: 'Más natural que "What is your job?". En confianza basta con "What do you do?".',
        },
        {
          en: "I'm self-employed.",
          es: 'Trabajo por cuenta propia.',
          kind: 'phrase',
          example: { en: "I'm self-employed, so I choose my own hours.", es: 'Trabajo por cuenta propia, así que elijo mi horario.' },
        },
      ],
    },
    {
      title: 'En la oficina',
      emoji: '🏢',
      items: [
        {
          en: 'coworker',
          es: 'compañero de trabajo',
          kind: 'word',
          example: { en: 'My coworkers and I have lunch together on Fridays.', es: 'Mis compañeros de trabajo y yo almorzamos juntos los viernes.' },
          alt: ['colleague', 'co-worker'],
          note: '"Colleague" es un sinónimo un poco más formal.',
        },
        {
          en: 'boss',
          es: 'jefe',
          kind: 'word',
          example: { en: 'My boss wants the report this afternoon.', es: 'Mi jefe quiere el informe esta tarde.' },
        },
        {
          en: 'stapler',
          es: 'engrapadora',
          kind: 'word',
          example: { en: 'Can I borrow your stapler for a second?', es: '¿Me prestas tu engrapadora un segundo?' },
        },
        {
          en: "I'm working from home today.",
          es: 'Hoy trabajo desde casa.',
          kind: 'phrase',
          example: { en: "I'm working from home today, so call my cell.", es: 'Hoy trabajo desde casa, así que llama a mi celular.' },
          note: 'En chats de trabajo se abrevia WFH (working from home).',
        },
        {
          en: 'I need to make some copies.',
          es: 'Necesito sacar unas copias.',
          kind: 'phrase',
          example: { en: 'I need to make some copies before the meeting.', es: 'Necesito sacar unas copias antes de la reunión.' },
          note: 'Se dice "make copies", no "take copies".',
        },
      ],
    },
    {
      title: 'Reuniones',
      emoji: '👥',
      items: [
        {
          en: 'meeting',
          es: 'reunión',
          kind: 'word',
          example: { en: 'The meeting starts at ten in room B.', es: 'La reunión empieza a las diez en la sala B.' },
        },
        {
          en: 'agenda',
          es: 'orden del día',
          kind: 'word',
          example: { en: 'The first item on the agenda is the budget.', es: 'El primer punto del orden del día es el presupuesto.' },
          note: 'Falso amigo: "agenda" es el orden del día; la libreta para anotar citas es "planner".',
        },
        {
          en: 'conference room',
          es: 'sala de juntas',
          kind: 'word',
          example: { en: "We're meeting in the conference room after lunch.", es: 'Nos reunimos en la sala de juntas después del almuerzo.' },
          alt: ['meeting room'],
        },
        {
          en: "Let's get started.",
          es: 'Empecemos.',
          kind: 'phrase',
          example: { en: "Okay, everyone's here. Let's get started.", es: 'Bueno, ya están todos. Empecemos.' },
          alt: ["Let's begin.", "Let's start."],
        },
        {
          en: 'Does anyone have any questions?',
          es: '¿Alguien tiene alguna pregunta?',
          kind: 'phrase',
          example: { en: "That's all from me. Does anyone have any questions?", es: 'Eso es todo de mi parte. ¿Alguien tiene alguna pregunta?' },
        },
      ],
    },
    {
      title: 'Correos electrónicos',
      emoji: '📧',
      items: [
        {
          en: 'attachment',
          es: 'archivo adjunto',
          kind: 'word',
          example: { en: 'I forgot to include the attachment in my email.', es: 'Olvidé incluir el archivo adjunto en mi correo.' },
        },
        {
          en: 'inbox',
          es: 'bandeja de entrada',
          kind: 'word',
          example: { en: 'My inbox is full of unread messages.', es: 'Mi bandeja de entrada está llena de mensajes sin leer.' },
        },
        {
          en: 'to forward',
          es: 'reenviar',
          kind: 'word',
          example: { en: "Could you forward me the client's email?", es: '¿Podrías reenviarme el correo del cliente?' },
          note: 'Responder es "to reply"; enviar el correo a otra persona es "to forward".',
        },
        {
          en: 'Please find the report attached.',
          es: 'Adjunto el informe.',
          kind: 'phrase',
          example: { en: 'Hi Mark, please find the report attached. Best, Ana.', es: 'Hola, Mark: adjunto el informe. Saludos, Ana.' },
          alt: ["I've attached the report.", 'Attached is the report.'],
          note: 'Fórmula típica de correos formales. Más sencillo: "I\'ve attached the report."',
        },
        {
          en: 'Thank you for your quick reply.',
          es: 'Gracias por su pronta respuesta.',
          kind: 'phrase',
          example: { en: 'Dear Ms. Lee, thank you for your quick reply.', es: 'Estimada Sra. Lee: gracias por su pronta respuesta.' },
          alt: ['Thanks for your quick reply.', 'Thank you for your prompt reply.'],
        },
      ],
    },
    {
      title: 'Llamadas',
      emoji: '📞',
      items: [
        {
          en: 'voicemail',
          es: 'buzón de voz',
          kind: 'word',
          example: { en: 'I left a message on your voicemail.', es: 'Te dejé un mensaje en el buzón de voz.' },
        },
        {
          en: 'extension',
          es: 'extensión (telefónica)',
          kind: 'word',
          example: { en: 'Please call me at extension 204.', es: 'Por favor, llámame a la extensión 204.' },
        },
        {
          en: 'to dial',
          es: 'marcar (un número)',
          kind: 'word',
          example: { en: 'Dial the area code first, then the number.', es: 'Marca primero el código de área y luego el número.' },
        },
        {
          en: "Who's calling, please?",
          es: '¿De parte de quién?',
          kind: 'phrase',
          example: { en: "Can I speak to Mr. Ruiz? — Who's calling, please?", es: '¿Puedo hablar con el Sr. Ruiz? —¿De parte de quién?' },
          alt: ['May I ask who is calling?'],
          note: 'Para identificarte al teléfono se dice "This is Ana", no "I am Ana".',
        },
        {
          en: 'Can I take a message?',
          es: '¿Quiere dejar un mensaje?',
          kind: 'phrase',
          example: { en: "She's in a meeting right now. Can I take a message?", es: 'Ella está en una reunión ahora. ¿Quiere dejar un mensaje?' },
          alt: ['Would you like to leave a message?', 'May I take a message?'],
        },
      ],
    },
    {
      title: 'Entrevista de trabajo',
      emoji: '🤝',
      items: [
        {
          en: 'résumé',
          es: 'currículum',
          kind: 'word',
          example: { en: 'Please send your résumé before Friday.', es: 'Por favor, envíe su currículum antes del viernes.' },
          alt: ['resume', 'CV'],
          note: 'En EE. UU. se dice "résumé"; en el Reino Unido, "CV".',
        },
        {
          en: 'salary',
          es: 'salario',
          kind: 'word',
          example: { en: 'The salary is good, but the hours are long.', es: 'El salario es bueno, pero las jornadas son largas.' },
        },
        {
          en: 'to hire',
          es: 'contratar',
          kind: 'word',
          example: { en: 'The company is hiring two new designers.', es: 'La empresa está contratando a dos diseñadores nuevos.' },
          note: 'Lo contrario es "to fire" (despedir).',
        },
        {
          en: 'Tell me about yourself.',
          es: 'Hábleme de usted.',
          kind: 'phrase',
          example: { en: 'Good morning. Please sit down and tell me about yourself.', es: 'Buenos días. Siéntese, por favor, y hábleme de usted.' },
          note: 'Pregunta clásica de entrevista: resume tu experiencia y estudios en un minuto.',
        },
        {
          en: "I'm a fast learner.",
          es: 'Aprendo rápido.',
          kind: 'phrase',
          example: { en: "I don't have much experience, but I'm a fast learner.", es: 'No tengo mucha experiencia, pero aprendo rápido.' },
          alt: ['I learn quickly.', 'I learn fast.'],
        },
      ],
    },
    {
      title: 'En clase',
      emoji: '🎓',
      items: [
        {
          en: 'homework',
          es: 'tarea',
          kind: 'word',
          example: { en: 'We have a lot of homework for tomorrow.', es: 'Tenemos mucha tarea para mañana.' },
          note: 'Es incontable y se usa con "do": "do your homework", nunca "homeworks".',
        },
        {
          en: 'classmate',
          es: 'compañero de clase',
          kind: 'word',
          example: { en: 'My classmate helped me with the project.', es: 'Mi compañero de clase me ayudó con el proyecto.' },
        },
        {
          en: 'grade',
          es: 'calificación',
          kind: 'word',
          example: { en: 'She got a good grade on her math test.', es: 'Sacó una buena calificación en su examen de matemáticas.' },
          alt: ['mark'],
          note: '"Grade" también es el año escolar: "She\'s in fifth grade."',
        },
        {
          en: 'I passed the exam!',
          es: '¡Aprobé el examen!',
          kind: 'phrase',
          example: { en: 'Great news, Mom! I passed the exam!', es: '¡Buenas noticias, mamá! ¡Aprobé el examen!' },
          alt: ['I passed the test!'],
          note: 'Falso amigo: "to pass" es aprobar. Reprobar es "to fail".',
        },
        {
          en: 'Work in pairs, please.',
          es: 'Trabajen en parejas, por favor.',
          kind: 'phrase',
          example: { en: 'Open your books to page 20 and work in pairs, please.', es: 'Abran sus libros en la página 20 y trabajen en parejas, por favor.' },
        },
      ],
    },
    {
      title: 'Tecnología',
      emoji: '💻',
      items: [
        {
          en: 'password',
          es: 'contraseña',
          kind: 'word',
          example: { en: 'Never share your password with anyone.', es: 'Nunca compartas tu contraseña con nadie.' },
        },
        {
          en: 'to download',
          es: 'descargar',
          kind: 'word',
          example: { en: 'You can download the app for free.', es: 'Puedes descargar la aplicación gratis.' },
          note: 'Lo contrario es "to upload" (subir un archivo).',
        },
        {
          en: 'to log in',
          es: 'iniciar sesión',
          kind: 'word',
          example: { en: "I can't log in to my work account.", es: 'No puedo iniciar sesión en mi cuenta del trabajo.' },
          alt: ['to sign in'],
          note: 'Para cerrar sesión se dice "to log out".',
        },
        {
          en: 'My computer froze.',
          es: 'Se me congeló la computadora.',
          kind: 'phrase',
          example: { en: 'My computer froze and I lost my work.', es: 'Se me congeló la computadora y perdí mi trabajo.' },
          note: '"Froze" es el pasado irregular de "freeze" (congelarse).',
        },
        {
          en: 'Have you tried restarting it?',
          es: '¿Ya intentaste reiniciarlo?',
          kind: 'phrase',
          example: { en: 'My phone is really slow. — Have you tried restarting it?', es: 'Mi teléfono está muy lento. —¿Ya intentaste reiniciarlo?' },
        },
      ],
    },
    {
      title: 'Proyectos y plazos',
      emoji: '📅',
      items: [
        {
          en: 'deadline',
          es: 'fecha límite',
          kind: 'word',
          example: { en: 'The deadline for the project is next Friday.', es: 'La fecha límite del proyecto es el próximo viernes.' },
        },
        {
          en: 'budget',
          es: 'presupuesto',
          kind: 'word',
          example: { en: 'We need to stay within the budget.', es: 'Necesitamos mantenernos dentro del presupuesto.' },
        },
        {
          en: 'to postpone',
          es: 'posponer',
          kind: 'word',
          example: { en: 'They postponed the launch until March.', es: 'Pospusieron el lanzamiento hasta marzo.' },
        },
        {
          en: "We're behind schedule.",
          es: 'Vamos atrasados con el cronograma.',
          kind: 'phrase',
          example: { en: "We're behind schedule, so we need to work faster.", es: 'Vamos atrasados con el cronograma, así que debemos trabajar más rápido.' },
          note: 'Lo contrario es "We\'re ahead of schedule" (vamos adelantados).',
        },
        {
          en: "I'll have it ready by Monday.",
          es: 'Lo tendré listo para el lunes.',
          kind: 'phrase',
          example: { en: "Don't worry about the report. I'll have it ready by Monday.", es: 'No te preocupes por el informe. Lo tendré listo para el lunes.' },
          note: '"By" + fecha indica el límite: "a más tardar el lunes".',
        },
      ],
    },
    {
      title: 'Opiniones en el trabajo',
      emoji: '💡',
      items: [
        {
          en: 'feedback',
          es: 'retroalimentación',
          kind: 'word',
          example: { en: 'Thanks for your feedback on my presentation.', es: 'Gracias por tu retroalimentación sobre mi presentación.' },
          note: 'Es incontable: "some feedback", no "a feedback". También se traduce como "comentarios".',
        },
        {
          en: 'proposal',
          es: 'propuesta',
          kind: 'word',
          example: { en: 'The manager approved our proposal for the new website.', es: 'El gerente aprobó nuestra propuesta para el nuevo sitio web.' },
        },
        {
          en: 'approach',
          es: 'enfoque',
          kind: 'word',
          example: { en: 'I think we need a different approach.', es: 'Creo que necesitamos un enfoque diferente.' },
        },
        {
          en: 'Could I make a suggestion?',
          es: '¿Puedo hacer una sugerencia?',
          kind: 'phrase',
          example: { en: "Could I make a suggestion? Let's ask the client first.", es: '¿Puedo hacer una sugerencia? Preguntemos primero al cliente.' },
          alt: ['May I make a suggestion?', 'Can I make a suggestion?'],
        },
        {
          en: 'I have some concerns about this plan.',
          es: 'Tengo algunas inquietudes sobre este plan.',
          kind: 'phrase',
          example: { en: 'I have some concerns about this plan. It seems too expensive.', es: 'Tengo algunas inquietudes sobre este plan. Parece demasiado caro.' },
          note: 'Forma diplomática de mostrar dudas o desacuerdo en el trabajo.',
        },
      ],
    },
  ],
}
