import type { LevelInput } from '../types'

export const level3: LevelInput = {
  id: 3,
  title: 'En la ciudad',
  subtitle: 'Muévete por la ciudad, haz compras y resuelve trámites.',
  cefr: 'A2',
  emoji: '🏙️',
  color: 'violet',
  lessons: [
    {
      title: 'Lugares',
      emoji: '🏛️',
      items: [
        {
          en: 'library',
          es: 'biblioteca',
          kind: 'word',
          example: { en: 'I study at the library on Saturdays.', es: 'Estudio en la biblioteca los sábados.' },
          note: 'Falso amigo: "library" es biblioteca; librería se dice "bookstore".',
        },
        {
          en: 'city hall',
          es: 'alcaldía',
          kind: 'word',
          example: { en: 'We need to go to city hall tomorrow.', es: 'Tenemos que ir a la alcaldía mañana.' },
          alt: ['town hall'],
        },
        {
          en: 'downtown',
          es: 'centro (de la ciudad)',
          kind: 'word',
          example: { en: 'I work downtown, near the main square.', es: 'Trabajo en el centro, cerca de la plaza principal.' },
          alt: ['city center'],
          note: 'Se usa sin "the" ni "to": "I work downtown", "Let\'s go downtown".',
        },
        {
          en: 'Is there a park near here?',
          es: '¿Hay un parque cerca de aquí?',
          kind: 'phrase',
          example: { en: 'Is there a park near here? — Yes, two blocks away.', es: '¿Hay un parque cerca de aquí? —Sí, a dos cuadras.' },
          alt: ['Is there a park nearby?'],
        },
        {
          en: 'I live in the suburbs.',
          es: 'Vivo en las afueras.',
          kind: 'phrase',
          example: { en: 'I live in the suburbs, so I take the train.', es: 'Vivo en las afueras, así que tomo el tren.' },
          alt: ['I live on the outskirts.'],
          note: '"Suburbs" son zonas residenciales, no "suburbios" (barrios pobres).',
        },
      ],
    },
    {
      title: 'Direcciones',
      emoji: '🧭',
      items: [
        {
          en: 'corner',
          es: 'esquina',
          kind: 'word',
          example: { en: 'The pharmacy is on the corner.', es: 'La farmacia está en la esquina.' },
          note: '"On the corner" = en la esquina (de la calle); "in the corner" = en el rincón.',
        },
        {
          en: 'block',
          es: 'cuadra',
          kind: 'word',
          example: { en: 'The bank is three blocks from here.', es: 'El banco está a tres cuadras de aquí.' },
        },
        {
          en: 'traffic light',
          es: 'semáforo',
          kind: 'word',
          example: { en: 'Turn right at the traffic light.', es: 'Dobla a la derecha en el semáforo.' },
        },
        {
          en: 'How do I get to the station?',
          es: '¿Cómo llego a la estación?',
          kind: 'phrase',
          example: { en: 'Excuse me, how do I get to the station?', es: 'Disculpe, ¿cómo llego a la estación?' },
          alt: ['How can I get to the station?'],
        },
        {
          en: 'Turn left at the corner.',
          es: 'Dobla a la izquierda en la esquina.',
          kind: 'phrase',
          example: { en: 'Go straight ahead and turn left at the corner.', es: 'Sigue derecho y dobla a la izquierda en la esquina.' },
          note: 'Ojo: "right" es derecha, pero "straight" es derecho (recto).',
        },
      ],
    },
    {
      title: 'Transporte',
      emoji: '🚌',
      items: [
        {
          en: 'bus stop',
          es: 'parada de autobús',
          kind: 'word',
          example: { en: "I'll wait for you at the bus stop.", es: 'Te espero en la parada de autobús.' },
        },
        {
          en: 'subway',
          es: 'metro',
          kind: 'word',
          example: { en: 'The subway is faster than the bus.', es: 'El metro es más rápido que el autobús.' },
          alt: ['metro'],
          note: 'En Reino Unido se dice "the underground" o "the tube".',
        },
        {
          en: 'to get off',
          es: 'bajarse',
          kind: 'word',
          example: { en: 'We get off at the next stop.', es: 'Nos bajamos en la próxima parada.' },
          note: 'Lo contrario es "to get on" (subirse al autobús o al tren).',
        },
        {
          en: 'Does this bus go downtown?',
          es: '¿Este autobús va al centro?',
          kind: 'phrase',
          example: { en: 'Does this bus go downtown? — No, take the number 12.', es: '¿Este autobús va al centro? —No, toma el número 12.' },
        },
        {
          en: 'How often does the bus come?',
          es: '¿Cada cuánto pasa el autobús?',
          kind: 'phrase',
          example: { en: 'How often does the bus come? — Every ten minutes.', es: '¿Cada cuánto pasa el autobús? —Cada diez minutos.' },
          alt: ['How often does the bus run?'],
        },
      ],
    },
    {
      title: 'De compras',
      emoji: '🛍️',
      items: [
        {
          en: 'cash',
          es: 'efectivo',
          kind: 'word',
          example: { en: 'Sorry, I only have cash.', es: 'Lo siento, solo tengo efectivo.' },
        },
        {
          en: 'receipt',
          es: 'recibo',
          kind: 'word',
          example: { en: 'Keep your receipt if you want to return it.', es: 'Guarda tu recibo si quieres devolverlo.' },
          note: 'Se pronuncia /ri-SÍT/: la "p" no suena.',
        },
        {
          en: 'on sale',
          es: 'en oferta',
          kind: 'word',
          example: { en: 'These jackets are on sale this week.', es: 'Estas chaquetas están en oferta esta semana.' },
          note: '"On sale" = con descuento; "for sale" = a la venta.',
        },
        {
          en: 'Can I pay by card?',
          es: '¿Puedo pagar con tarjeta?',
          kind: 'phrase',
          example: { en: 'Can I pay by card? — Yes, of course.', es: '¿Puedo pagar con tarjeta? —Sí, claro.' },
          alt: ['Can I pay with a card?', 'Can I pay by credit card?'],
        },
        {
          en: "I'm just looking, thanks.",
          es: 'Solo estoy mirando, gracias.',
          kind: 'phrase',
          example: { en: "Can I help you? — I'm just looking, thanks.", es: '¿Le puedo ayudar? —Solo estoy mirando, gracias.' },
          alt: ["I'm just looking, thank you."],
        },
      ],
    },
    {
      title: 'En el supermercado',
      emoji: '🛒',
      items: [
        {
          en: 'shopping cart',
          es: 'carrito de compras',
          kind: 'word',
          example: { en: 'Put the water in the shopping cart.', es: 'Pon el agua en el carrito de compras.' },
          alt: ['cart'],
        },
        {
          en: 'aisle',
          es: 'pasillo',
          kind: 'word',
          example: { en: 'The rice is in aisle five.', es: 'El arroz está en el pasillo cinco.' },
          note: 'Se pronuncia /áil/, como "I\'ll": la "s" no suena.',
        },
        {
          en: 'expiration date',
          es: 'fecha de vencimiento',
          kind: 'word',
          example: { en: 'Always check the expiration date on the milk.', es: 'Siempre revisa la fecha de vencimiento de la leche.' },
          alt: ['expiry date'],
        },
        {
          en: 'Where can I find the eggs?',
          es: '¿Dónde puedo encontrar los huevos?',
          kind: 'phrase',
          example: { en: 'Where can I find the eggs? — Next to the milk.', es: '¿Dónde puedo encontrar los huevos? —Junto a la leche.' },
          alt: ['Where are the eggs?'],
        },
        {
          en: 'Do you need a bag?',
          es: '¿Necesita una bolsa?',
          kind: 'phrase',
          example: { en: 'Do you need a bag? — No, thanks, I have one.', es: '¿Necesita una bolsa? —No, gracias, tengo una.' },
        },
      ],
    },
    {
      title: 'En el restaurante',
      emoji: '🍽️',
      items: [
        {
          en: 'waiter',
          es: 'mesero',
          kind: 'word',
          example: { en: 'The waiter brought us the menu.', es: 'El mesero nos trajo el menú.' },
          alt: ['server'],
          note: 'Para una mujer: "waitress". La palabra neutra "server" sirve para ambos.',
        },
        {
          en: 'tip',
          es: 'propina',
          kind: 'word',
          example: { en: 'We left a twenty percent tip.', es: 'Dejamos una propina del veinte por ciento.' },
          note: 'En EE. UU. se suele dejar entre 15 % y 20 % de propina.',
        },
        {
          en: 'A table for two, please.',
          es: 'Una mesa para dos, por favor.',
          kind: 'phrase',
          example: { en: 'Good evening. A table for two, please.', es: 'Buenas noches. Una mesa para dos, por favor.' },
        },
        {
          en: 'Are you ready to order?',
          es: '¿Están listos para pedir?',
          kind: 'phrase',
          example: { en: "Are you ready to order? — Yes, I'd like the soup.", es: '¿Están listos para pedir? —Sí, quisiera la sopa.' },
        },
        {
          en: 'Can we have the check, please?',
          es: '¿Nos trae la cuenta, por favor?',
          kind: 'phrase',
          example: { en: "We're finished. Can we have the check, please?", es: 'Ya terminamos. ¿Nos trae la cuenta, por favor?' },
          alt: ['Could we have the check, please?', 'Can we get the check, please?', 'Can we have the bill, please?'],
          note: 'En EE. UU. se dice "check"; en Reino Unido, "bill".',
        },
      ],
    },
    {
      title: 'En el banco',
      emoji: '🏦',
      items: [
        {
          en: 'bank account',
          es: 'cuenta bancaria',
          kind: 'word',
          example: { en: 'I need a bank account for my salary.', es: 'Necesito una cuenta bancaria para mi sueldo.' },
        },
        {
          en: 'ATM',
          es: 'cajero automático',
          kind: 'word',
          example: { en: 'I took out money from the ATM.', es: 'Saqué dinero del cajero automático.' },
          alt: ['cash machine'],
        },
        {
          en: 'to withdraw',
          es: 'retirar (dinero)',
          kind: 'word',
          example: { en: 'I want to withdraw two hundred dollars.', es: 'Quiero retirar doscientos dólares.' },
          alt: ['to take out'],
          note: 'Pasado irregular: withdrew. En el día a día también se dice "to take out money".',
        },
        {
          en: "I'd like to open an account.",
          es: 'Quisiera abrir una cuenta.',
          kind: 'phrase',
          example: { en: "Good morning. I'd like to open an account.", es: 'Buenos días. Quisiera abrir una cuenta.' },
          alt: ['I want to open an account.'],
        },
        {
          en: 'I forgot my PIN.',
          es: 'Olvidé mi PIN.',
          kind: 'phrase',
          example: { en: "I forgot my PIN, so I can't use my card.", es: 'Olvidé mi PIN, así que no puedo usar mi tarjeta.' },
        },
      ],
    },
    {
      title: 'En la farmacia',
      emoji: '💊',
      items: [
        {
          en: 'prescription',
          es: 'receta médica',
          kind: 'word',
          example: { en: 'You need a prescription for this medicine.', es: 'Necesitas una receta médica para este medicamento.' },
          note: 'Falso amigo: "recipe" es receta de cocina, no receta médica.',
        },
        {
          en: 'painkiller',
          es: 'analgésico',
          kind: 'word',
          example: { en: 'Take a painkiller and rest.', es: 'Toma un analgésico y descansa.' },
          alt: ['pain reliever'],
        },
        {
          en: 'cough syrup',
          es: 'jarabe para la tos',
          kind: 'word',
          example: { en: 'This cough syrup tastes terrible.', es: 'Este jarabe para la tos sabe horrible.' },
        },
        {
          en: 'I have a sore throat.',
          es: 'Me duele la garganta.',
          kind: 'phrase',
          example: { en: 'I have a sore throat. Do you have anything for it?', es: 'Me duele la garganta. ¿Tiene algo para eso?' },
          alt: ['My throat hurts.'],
        },
        {
          en: 'How often should I take it?',
          es: '¿Cada cuánto debo tomarlo?',
          kind: 'phrase',
          example: { en: 'How often should I take it? — Every eight hours.', es: '¿Cada cuánto debo tomarlo? —Cada ocho horas.' },
          alt: ['How often do I take it?'],
        },
      ],
    },
    {
      title: 'Correo y trámites',
      emoji: '📮',
      items: [
        {
          en: 'post office',
          es: 'oficina de correos',
          kind: 'word',
          example: { en: 'The post office closes at five.', es: 'La oficina de correos cierra a las cinco.' },
        },
        {
          en: 'stamp',
          es: 'estampilla',
          kind: 'word',
          example: { en: 'I need two stamps for these letters.', es: 'Necesito dos estampillas para estas cartas.' },
        },
        {
          en: 'to fill out',
          es: 'llenar (un formulario)',
          kind: 'word',
          example: { en: 'Please fill out this form.', es: 'Por favor, llene este formulario.' },
          alt: ['to fill in'],
          note: 'En inglés británico se dice "to fill in".',
        },
        {
          en: "I'd like to mail this package.",
          es: 'Quisiera enviar este paquete.',
          kind: 'phrase',
          example: { en: "I'd like to mail this package to Colombia.", es: 'Quisiera enviar este paquete a Colombia.' },
          alt: ["I'd like to send this package."],
          note: 'En EE. UU. se dice "to mail"; en Reino Unido, "to post".',
        },
        {
          en: 'What documents do I need?',
          es: '¿Qué documentos necesito?',
          kind: 'phrase',
          example: { en: 'What documents do I need? — Your ID and a photo.', es: '¿Qué documentos necesito? —Su identificación y una foto.' },
        },
      ],
    },
    {
      title: 'Vecinos y comunidad',
      emoji: '🏘️',
      items: [
        {
          en: 'neighbor',
          es: 'vecino',
          kind: 'word',
          example: { en: 'My neighbor has a big dog.', es: 'Mi vecino tiene un perro grande.' },
          alt: ['neighbour'],
        },
        {
          en: 'neighborhood',
          es: 'barrio',
          kind: 'word',
          example: { en: "It's a quiet neighborhood with lots of trees.", es: 'Es un barrio tranquilo con muchos árboles.' },
          alt: ['neighbourhood'],
        },
        {
          en: 'noisy',
          es: 'ruidoso',
          kind: 'word',
          example: { en: 'The street is very noisy at night.', es: 'La calle es muy ruidosa de noche.' },
        },
        {
          en: 'I just moved in next door.',
          es: 'Acabo de mudarme al lado.',
          kind: 'phrase',
          example: { en: "Hi! I'm Ana. I just moved in next door.", es: '¡Hola! Soy Ana. Acabo de mudarme al lado.' },
          alt: ['I just moved next door.'],
        },
        {
          en: 'Could you turn the music down, please?',
          es: '¿Podrías bajar la música, por favor?',
          kind: 'phrase',
          example: { en: "It's late. Could you turn the music down, please?", es: 'Es tarde. ¿Podrías bajar la música, por favor?' },
          alt: ['Could you turn down the music, please?', 'Can you turn the music down, please?'],
        },
      ],
    },
  ],
}
