import type { LevelInput } from '../types'

export const level1: LevelInput = {
  id: 1,
  title: 'Primeros pasos',
  subtitle: 'Saluda, preséntate y da tus primeros pasos en inglés.',
  cefr: 'A1',
  emoji: '👋',
  color: 'emerald',
  lessons: [
    {
      title: 'Saludos',
      emoji: '👋',
      items: [
        {
          en: 'hello',
          es: 'hola',
          kind: 'word',
          example: { en: 'Hello, my name is Tom.', es: 'Hola, me llamo Tom.' },
          alt: ['hi'],
        },
        {
          en: 'goodbye',
          es: 'adiós',
          kind: 'word',
          example: { en: 'Goodbye, Anna! See you later.', es: '¡Adiós, Anna! Hasta luego.' },
          alt: ['bye'],
        },
        {
          en: 'Good morning!',
          es: '¡Buenos días!',
          kind: 'phrase',
          example: { en: 'Good morning, Mr. Brown!', es: '¡Buenos días, señor Brown!' },
        },
        {
          en: 'Good night!',
          es: '¡Buenas noches!',
          kind: 'phrase',
          example: { en: 'Good night, Mom! See you tomorrow.', es: '¡Buenas noches, mamá! Hasta mañana.' },
          note: 'Solo para despedirse o al ir a dormir. Para saludar de noche se dice "Good evening".',
        },
        {
          en: 'How are you?',
          es: '¿Cómo estás?',
          kind: 'phrase',
          example: { en: "How are you? I'm fine, thanks.", es: '¿Cómo estás? Estoy bien, gracias.' },
        },
      ],
    },
    {
      title: 'Cortesía',
      emoji: '🙏',
      items: [
        {
          en: 'please',
          es: 'por favor',
          kind: 'word',
          example: { en: 'A coffee, please.', es: 'Un café, por favor.' },
        },
        {
          en: 'thank you',
          es: 'gracias',
          kind: 'word',
          example: { en: 'Thank you very much!', es: '¡Muchas gracias!' },
          alt: ['thanks'],
        },
        {
          en: 'sorry',
          es: 'lo siento',
          kind: 'word',
          example: { en: "I'm so sorry!", es: '¡Lo siento mucho!' },
        },
        {
          en: 'Excuse me.',
          es: 'Disculpe.',
          kind: 'phrase',
          example: { en: 'Excuse me, are you Mr. Lee?', es: 'Disculpe, ¿es usted el señor Lee?' },
          note: 'Para pedir permiso o llamar la atención. Para disculparte por un error, usa "sorry".',
        },
        {
          en: "You're welcome.",
          es: 'De nada.',
          kind: 'phrase',
          example: { en: "You're welcome, Tom! Have a nice day.", es: '¡De nada, Tom! Que tengas un buen día.' },
        },
      ],
    },
    {
      title: 'Presentarse',
      emoji: '🙋',
      items: [
        {
          en: 'name',
          es: 'nombre',
          kind: 'word',
          example: { en: 'My name is Laura.', es: 'Mi nombre es Laura.' },
        },
        {
          en: 'last name',
          es: 'apellido',
          kind: 'word',
          example: { en: 'My last name is Smith.', es: 'Mi apellido es Smith.' },
          alt: ['surname'],
        },
        {
          en: "What's your name?",
          es: '¿Cómo te llamas?',
          kind: 'phrase',
          example: { en: "Hi! What's your name? I'm Sofia.", es: '¡Hola! ¿Cómo te llamas? Soy Sofía.' },
        },
        {
          en: 'Nice to meet you.',
          es: 'Mucho gusto.',
          kind: 'phrase',
          example: { en: "I'm Tom. Nice to meet you.", es: 'Soy Tom. Mucho gusto.' },
          alt: ['Pleased to meet you.'],
          note: 'Se responde con "Nice to meet you too."',
        },
        {
          en: "I'm from Mexico.",
          es: 'Soy de México.',
          kind: 'phrase',
          example: { en: "Where are you from? I'm from Mexico.", es: '¿De dónde eres? Soy de México.' },
        },
      ],
    },
    {
      title: 'Números',
      emoji: '🔢',
      items: [
        {
          en: 'three',
          es: 'tres',
          kind: 'word',
          example: { en: 'I have three brothers.', es: 'Tengo tres hermanos.' },
          note: 'La "th" se pronuncia con la punta de la lengua entre los dientes.',
        },
        {
          en: 'fifteen',
          es: 'quince',
          kind: 'word',
          example: { en: 'My sister is fifteen.', es: 'Mi hermana tiene quince años.' },
          note: 'No lo confundas con "fifty" (50). En "fifteen" la fuerza va al final: fif-TEEN.',
        },
        {
          en: 'twenty',
          es: 'veinte',
          kind: 'word',
          example: { en: 'There are twenty people here.', es: 'Hay veinte personas aquí.' },
        },
        {
          en: 'How old are you?',
          es: '¿Cuántos años tienes?',
          kind: 'phrase',
          example: { en: "How old are you? I'm ten.", es: '¿Cuántos años tienes? Tengo diez.' },
        },
        {
          en: "I'm thirty years old.",
          es: 'Tengo treinta años.',
          kind: 'phrase',
          example: { en: "Hi, I'm Ana. I'm thirty years old.", es: 'Hola, soy Ana. Tengo treinta años.' },
          alt: ["I'm thirty."],
          note: 'La edad se dice con "to be": "I am thirty", nunca "I have thirty".',
        },
      ],
    },
    {
      title: 'Colores',
      emoji: '🎨',
      items: [
        {
          en: 'red',
          es: 'rojo',
          kind: 'word',
          example: { en: 'She has a red car.', es: 'Ella tiene un auto rojo.' },
          note: 'El color va antes del sustantivo: "a red car" (un auto rojo).',
        },
        {
          en: 'blue',
          es: 'azul',
          kind: 'word',
          example: { en: 'The sky is blue.', es: 'El cielo es azul.' },
        },
        {
          en: 'black',
          es: 'negro',
          kind: 'word',
          example: { en: 'My cat is black.', es: 'Mi gato es negro.' },
        },
        {
          en: 'What color is it?',
          es: '¿De qué color es?',
          kind: 'phrase',
          example: { en: "What color is it? It's white.", es: '¿De qué color es? Es blanco.' },
          alt: ['What colour is it?'],
        },
        {
          en: 'My favorite color is green.',
          es: 'Mi color favorito es el verde.',
          kind: 'phrase',
          example: { en: 'My favorite color is green. What about you?', es: 'Mi color favorito es el verde. ¿Y el tuyo?' },
          alt: ['My favourite colour is green.'],
        },
      ],
    },
    {
      title: 'La familia',
      emoji: '👨‍👩‍👧',
      items: [
        {
          en: 'mother',
          es: 'madre',
          kind: 'word',
          example: { en: 'My mother is from Peru.', es: 'Mi madre es de Perú.' },
          alt: ['mom'],
        },
        {
          en: 'father',
          es: 'padre',
          kind: 'word',
          example: { en: 'My father is very tall.', es: 'Mi padre es muy alto.' },
          alt: ['dad'],
          note: 'Ojo: "parents" significa padres (papá y mamá), no "parientes".',
        },
        {
          en: 'brother',
          es: 'hermano',
          kind: 'word',
          example: { en: 'My brother is twelve.', es: 'Mi hermano tiene doce años.' },
        },
        {
          en: 'I have two sisters.',
          es: 'Tengo dos hermanas.',
          kind: 'phrase',
          example: { en: 'I have two sisters and one brother.', es: 'Tengo dos hermanas y un hermano.' },
        },
        {
          en: 'Do you have children?',
          es: '¿Tienes hijos?',
          kind: 'phrase',
          example: { en: 'Do you have children? Yes, two girls.', es: '¿Tienes hijos? Sí, dos niñas.' },
          note: '"Children" (hijos, niños) es el plural irregular de "child".',
        },
      ],
    },
    {
      title: 'Personas y pronombres',
      emoji: '👥',
      items: [
        {
          en: 'I',
          es: 'yo',
          kind: 'word',
          example: { en: 'I am Carlos.', es: 'Yo soy Carlos.' },
          note: '"I" siempre se escribe con mayúscula, incluso en medio de la oración.',
        },
        {
          en: 'you',
          es: 'tú',
          kind: 'word',
          example: { en: 'You are my friend.', es: 'Tú eres mi amigo.' },
          note: '"You" sirve para tú, usted y ustedes. El verbo no cambia.',
        },
        {
          en: 'we',
          es: 'nosotros',
          kind: 'word',
          example: { en: 'We are from Chile.', es: 'Nosotros somos de Chile.' },
        },
        {
          en: 'they',
          es: 'ellos',
          kind: 'word',
          example: { en: 'They are my parents.', es: 'Ellos son mis padres.' },
          note: '"They" sirve para ellos y ellas.',
        },
        {
          en: 'He is my friend.',
          es: 'Él es mi amigo.',
          kind: 'phrase',
          example: { en: 'This is Leo. He is my friend.', es: 'Este es Leo. Él es mi amigo.' },
        },
      ],
    },
    {
      title: 'Objetos cotidianos',
      emoji: '🔑',
      items: [
        {
          en: 'key',
          es: 'llave',
          kind: 'word',
          example: { en: 'I have the key.', es: 'Yo tengo la llave.' },
        },
        {
          en: 'book',
          es: 'libro',
          kind: 'word',
          example: { en: 'This book is very good.', es: 'Este libro es muy bueno.' },
        },
        {
          en: 'cell phone',
          es: 'celular',
          kind: 'word',
          example: { en: 'My cell phone is black.', es: 'Mi celular es negro.' },
          alt: ['cellphone', 'phone', 'mobile phone'],
        },
        {
          en: 'Is this your pen?',
          es: '¿Este es tu bolígrafo?',
          kind: 'phrase',
          example: { en: 'Excuse me, is this your pen?', es: 'Disculpe, ¿este es su bolígrafo?' },
        },
        {
          en: 'Where are my keys?',
          es: '¿Dónde están mis llaves?',
          kind: 'phrase',
          example: { en: "Where are my keys? I can't find them.", es: '¿Dónde están mis llaves? No las encuentro.' },
        },
      ],
    },
    {
      title: 'Preguntas básicas',
      emoji: '❓',
      items: [
        {
          en: 'what',
          es: 'qué',
          kind: 'word',
          example: { en: 'What is this?', es: '¿Qué es esto?' },
          note: 'A veces se traduce "cuál": "What is your name?" = ¿Cuál es tu nombre?',
        },
        {
          en: 'who',
          es: 'quién',
          kind: 'word',
          example: { en: 'Who is she?', es: '¿Quién es ella?' },
        },
        {
          en: 'why',
          es: 'por qué',
          kind: 'word',
          example: { en: 'Why are you here?', es: '¿Por qué estás aquí?' },
          note: 'Para responder "porque" se usa "because".',
        },
        {
          en: 'Where do you live?',
          es: '¿Dónde vives?',
          kind: 'phrase',
          example: { en: 'Where do you live? I live in Lima.', es: '¿Dónde vives? Vivo en Lima.' },
        },
        {
          en: "I don't know.",
          es: 'No sé.',
          kind: 'phrase',
          example: { en: "Where is Tom? I don't know.", es: '¿Dónde está Tom? No sé.' },
        },
      ],
    },
    {
      title: 'Comunicación básica',
      emoji: '💬',
      items: [
        {
          en: "I don't understand.",
          es: 'No entiendo.',
          kind: 'phrase',
          example: { en: "Sorry, I don't understand.", es: 'Perdón, no entiendo.' },
        },
        {
          en: 'Can you repeat that, please?',
          es: '¿Puedes repetirlo, por favor?',
          kind: 'phrase',
          example: { en: 'Sorry, can you repeat that, please?', es: 'Perdón, ¿puedes repetirlo, por favor?' },
          alt: ['Could you repeat that, please?'],
        },
        {
          en: 'Can you speak more slowly?',
          es: '¿Puedes hablar más despacio?',
          kind: 'phrase',
          example: { en: 'Can you speak more slowly, please?', es: '¿Puedes hablar más despacio, por favor?' },
          alt: ['Could you speak more slowly?', 'Can you speak slower?'],
        },
        {
          en: 'How do you say this in English?',
          es: '¿Cómo se dice esto en inglés?',
          kind: 'phrase',
          example: { en: 'Excuse me, how do you say this in English?', es: 'Disculpe, ¿cómo se dice esto en inglés?' },
        },
        {
          en: 'Do you speak Spanish?',
          es: '¿Hablas español?',
          kind: 'phrase',
          example: { en: 'Do you speak Spanish? Yes, a little.', es: '¿Hablas español? Sí, un poco.' },
          note: 'Los idiomas se escriben con mayúscula en inglés: Spanish, English.',
        },
      ],
    },
  ],
}
